#!/bin/bash
#

source ./scripts/helper

cd /roms/themes

dialog --backtitle "System" --infobox "\nDownloading nes-box ..." 5 55 > /dev/tty1
wget -q 'https://github.com/Jetup13/es-theme-nes-box/archive/master.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
sudo unzip -qq -o master.zip -d ./

dialog --backtitle "System" --infobox "\nCleaning up ..." 5 55 > /dev/tty1
rm -rf master.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5