#!/bin/bash

# Notes
#
export TERM=linux
sudo chmod 666 /dev/tty1

GamesMenu() {
	cmd=(dialog --clear --backtitle "AnberTheme" --title "[ Themes ]" --menu "Select theme from the list:" "15" "56" "15")

	options=(
		Back "Back to main menu"
		es-theme-arkos-carbon "Install/Update"
		es-theme-ChicueloAP "Install/Update"
		es-theme-custom-box "Install/Update"
		es-theme-epicnoir "Install/Update"
		es-theme-freeplay "Install/Update"
		es-theme-gbz35_mod "Install/Update"
		es-theme-magical-pixel "Install/Update"
		es-theme-minimal-arkos "Install/Update"
		es-theme-nes-box "Install/Update"
		es-theme-pixel "Install/Update"
		es-theme-solo-horizontal-arkos-ed "Install/Update"
		es-theme-switch "Install/Update"
	)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
   	bash ./scripts/themes/${choices[0]}
}

ExitMenu() {
	pgrep -f oga_controls | sudo xargs kill -9
	sudo systemctl restart emulationstation
}

UpdateMenu() {
	source ./scripts/helper

	dialog --backtitle "System" --infobox "\nDownloading latest release of AnberTheme ..." 5 55 > /dev/tty1
	wget -q 'https://github.com/TadMSTR/AnberThemes/releases/download/v1.0/AnberTheme.zip'

	dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
	unzip -qq -o AnberTheme.zip -d ../

	dialog --backtitle "System" --infobox "\nClearning up ..." 5 55 > /dev/tty1
	rm -rf AnberTheme.zip

	dialog --backtitle "System" --infobox "\nPlease launch AnberTheme again and enjoy ..." 5 55 > /dev/tty1
	sleep 5

	ExitMenu
}

source ./scripts/helper

#
# Joystick controls
#
sudo ./oga_controls &

#
# Main menu
#
while true; do
	cmd=(dialog --clear --backtitle "AnberTheme" --title " [ Main Menu ] " --menu "You can use UP/DOWN on the D-pad and A to select:" "10" "60" "10")

	options=(
		Themes "Install or update themes"
		Update "Check for updates"
		Exit "Exit to emulationstation"
	)

	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)

	for choice in $choices; do
		case $choice in
			Themes) GamesMenu ;;
			Update) UpdateMenu ;;
			Exit) ExitMenu ;;
		esac
	done
done
