#!/bin/bash

# Notes
#
export TERM=linux
sudo chmod 666 /dev/tty1 > /dev/null 2>&1

source ./scripts/helper

#
# Joystick controls
#
sudo ./oga_controls & > /dev/null 2>&1


function RemoveTheme () {
	local theme="$1"

	sudo sh -c 'printf "\033c" > /dev/tty1'
	printf "\nRemoving $theme ..."
    	sudo rm -rf "/roms/themes/$theme"
	printf "\n$theme removed !"
	
	sleep 3

	MainMenu

}

function UninstallMenu() {

	theme=(/roms/themes/*/)    # This creates an array of the full paths to all subdirs
	theme=("${theme[@]%/}")      # This removes the trailing slash on each item
	theme=("${theme[@]##*/}")    # This removes the path prefix, leaving just the dir names
	
	local options=()

	for theme in "${theme[@]}"; do
                options+=($theme "Uninstall")
        done


   	cmd=(dialog --clear --backtitle "AnberThemes" --title "[ Remove Themes ]" --menu "Select theme from the list:" "15" "56" "15")
    	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)

	retval=$?
	case $retval in
		0)
			RemoveTheme "${choices[0]}"
			;;
		1)
			MainMenu ;;

	esac
}

function InstallMenu() {
	
	local options=()

	local themes=(
	'es-theme-arkos-carbon'
	'es-theme-ChicueloAP'
	'es-theme-custom-box'
	'es-theme-epicnoir'
	'es-theme-freeplay'
	'es-theme-gbz35_mod'
	'es-theme-magical-pixel'
	'es-theme-minimal-arkos'
	'es-theme-nes-box'
	'es-theme-pixel'
	'es-theme-solo-horizontal-arkos-ed'
	'es-theme-switch'
	)

	for theme in "${themes[@]}"; do
            if [ -d "/roms/themes/$theme" ]
		then
                	options+=($theme "Update")
           	 else
                	options+=($theme "Install")
            fi
       done


	cmd=(dialog --clear --backtitle "AnberThemes" --title "[ Install Themes ]" --menu "Select theme from the list:" "15" "56" "15")
	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
		bash ./scripts/themes/${choices[0]}
		
	MainMenu
}

function ExitMenu() {
	pgrep -f oga_controls | sudo xargs kill -9 > /dev/null 2>&1
	sudo systemctl restart emulationstation
}

function UpdateAnberThemes() {

	UPDATE_URL="https://github.com/TadMSTR/AnberThemes/releases/download/v1.0/AnberThemes.zip"
	PAYLOAD=/dev/shm/payload_temp/*

	cd /roms/tools

	sudo sh -c 'printf "\033c" > /dev/tty1'
	printf "\nStarting update of AnberThemes..."
	mkdir -p /dev/shm/payload_temp #create a temp folder in RAM

	printf "\nDownloading archive for AnberThemes...\n"
	sudo wget -q "$UPDATE_URL" -O /dev/shm/payload_temp/update.zip
	if unzip -qt /dev/shm/payload_temp/update.zip | grep 'No errors detected';then
		printf "\nUnzipping archive..."
		sudo unzip -qo /dev/shm/payload_temp/update.zip -d /dev/shm/payload_temp/ #unzip directly in RAM
		rm /dev/shm/payload_temp/update.zip
		printf "\nOverwritting existing files..."
		cp -rf $PAYLOAD ./
		sudo chmod 777 ./*.sh #make sure newly downloaded scripts have right permission
		printf "\nAnberThemes updated successfully."
		sleep 3
	else
		printf "\nTheme update have failed because the archive did not download correctly."
		printf "\nCheck your connection and try again.\n"
		sleep 6
	fi
	printf "\nDeleting temporary files...\n"
	sudo rm -rf /dev/shm/payload_temp #remove the temp folder from RAM

	dialog --backtitle "System" --infobox "\nPlease launch AnberThemes again and enjoy ..." 5 55 > /dev/tty1
	sleep 5

	ExitMenu
}

function MainMenu () {

	cmd=(dialog --clear --backtitle "AnberThemes" --title " [ Main Menu ] " --menu "You can use UP/DOWN on the D-pad and A to select:" "10" "60" "10")

	options=(
		A "Install or update a theme"
		B "Uninstall a theme"
		C "Update AnberThemes"
		D "Exit to emulationstation"
	)

	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)

	retval=$?
	case $retval in
		0)
			for choice in $choices; do
				case $choice in
					A) InstallMenu ;;
					B) UninstallMenu ;;
					C) UpdateAnberThemes ;;
					D) ExitMenu ;;
				esac
			done
			;;
		1)
			ExitMenu ;;
	esac
}

MainMenu
