#!/bin/bash

# Notes
#
export TERM=linux
sudo chmod 666 /dev/tty1

ThemesMenu() {
	cmd=(dialog --clear --backtitle "AnberThemes" --title "[ Themes ]" --menu "Select theme from the list:" "15" "56" "15")

	options=(
		Back "Back to main menu"
		es-theme-arkos-carbon "Install or Update"
		es-theme-ChicueloAP "Install or Update"
		es-theme-custom-box "Install or Update"
		es-theme-epicnoir "Install or Update"
		es-theme-freeplay "Install or Update"
		es-theme-gbz35_mod "Install or Update"
		es-theme-magical-pixel "Install or Update"
		es-theme-minimal-arkos "Install or Update"
		es-theme-nes-box "Install or Update"
		es-theme-pixel "Install or Update"
		es-theme-solo-horizontal-arkos-ed "Install or Update"
		es-theme-switch "Install or Update"
	)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)
   	bash ./scripts/themes/${choices[0]}
}

ExitMenu() {
	pgrep -f oga_controls | sudo xargs kill -9
	sudo systemctl restart emulationstation
}

UpdateMenu() {
	source ./scripts/helper

	UPDATE_URL="https://github.com/tadmstr/AnberThemes/releases/download/v1.0/AnberThemes.zip"
	PAYLOAD=/dev/shm/payload_temp/*

	sudo sh -c 'printf "\033c" > /dev/tty1'
	printf "\nStarting update of AnberThemes..."
	mkdir -p /dev/shm/payload_temp #create a temp folder in RAM

	printf "\nDownloading archive for AnberThemes...\n"
	sudo wget -q "$UPDATE_URL" -O /dev/shm/payload_temp/update.zip
	if unzip -qt /dev/shm/payload_temp/update.zip | grep 'No errors detected';then
		printf "\nUnzipping archive..."
		sudo unzip -qo /dev/shm/payload_temp/update.zip -d /dev/shm/payload_temp/ #unzip directly in RAM
		rm /dev/shm/payload_temp/update.zip
		printf "\nOverwritting existing files..."
		cp -rf $PAYLOAD ../
		sudo chmod 777 ../*.sh #make sure newly downloaded scripts have right permission
		printf "\nAnberThemes updated successfully."
		sleep 3
	else
		printf "\nTheme update have failed because the archive did not download correctly."
		printf "\nCheck your connection and try again.\n"
		sleep 6
	fi
	printf "\nDeleting temporary files...\n"
	sudo rm -rf /dev/shm/payload_temp #remove the temp folder from RAM

	dialog --backtitle "System" --infobox "\nPlease launch AnberTheme again and enjoy ..." 5 55 > /dev/tty1
	sleep 5

	ExitMenu
}

source ./scripts/helper

#
# Joystick controls
#
sudo ./oga_controls &

#
# Main menu
#
while true; do
	cmd=(dialog --clear --backtitle "AnberThemes" --title " [ Main Menu ] " --menu "You can use UP/DOWN on the D-pad and A to select:" "10" "60" "10")

	options=(
		Themes "Install or update themes"
		Update "Check for updates"
		Exit "Exit to emulationstation"
	)

	choices=$("${cmd[@]}" "${options[@]}" 2>&1 > /dev/tty1)

	for choice in $choices; do
		case $choice in
			Themes) ThemesMenu ;;
			Update) UpdateMenu ;;
			Exit) ExitMenu ;;
		esac
	done
done
