#!/bin/bash
#

source ./scripts/helper

cd /roms/themes

dialog --backtitle "System" --infobox "\nDownloading solo-horizontal-arkos-ed ..." 5 55 > /dev/tty1
wget -q 'https://github.com/Jetup13/es-theme-solo-horizontal-arkos-ed/archive/main.zip'

dialog --backtitle "System" --infobox "\nExtracting ..." 5 55 > /dev/tty1
sudo unzip -qq -o main.zip -d ./

dialog --backtitle "System" --infobox "\nCleaning up ..." 5 55 > /dev/tty1
rm -rf main.zip

dialog --backtitle "System" --infobox "\nEnjoy! ..." 6 55 > /dev/tty1
sleep 5